### ISSUE TITLE
Why i couldn't start web-terminal?

### ISSUE THREAD

**Issue by thinhduckhoi** [rabchev/web-terminal#19]
Hello,
So after installing web-terminal based on the tutorials on homepage here:
https://www.terminal.com/webterminal
I started setting the different port 1991 and tried to access the IP-of-my-server:1991 but seems like it didn't work.
Even though i set it to 8282 port and gave it a try, it still don't work. I still couldn't access the web-terminal.

But then, i decided to create an absolutely new instance and tested again. This time, i was just accessing IP:8282 without setting port or anything and it worked.
Can you tell me what happend please?

**Comment by rabchev** [comment]
Hi thinhduckhoi,

This project is not associated with **terminal.com** in any way.  I think there is confusion because package names just happened to be identical, but please note that this is NPM (NodeJS) package while **terminal.com** are providing native DEB and RPM packages.

You should contact them for any issues related to their products.

**Comment by thinhduckhoi** [comment]
Oh sorry. I didn't notice that they were different packages. :+1:
