### ISSUE TITLE
Applications

### ISSUE THREAD

**Issue by capriciousduck** [rabchev/web-terminal#26]
Hi, I want to add more packages? Is it possible? Like tmux, wget, and other basic command line packages?

**Comment by rabchev** [comment]
Almost certainly tmux will not work because this implementation is not a TTY emulator and supports only subset of VT100 codes. As stated in the README file, you should consider other projects that fully implement TTY. This project is only good for learning and experimenting or some narrow specific tasks. There is a link in the readme file to the project I like best.

As for wget and other basic command line packages that do not interact with TTY besides outputting information on the stdout / stderr should work.
